import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const equipment={stovetop:'Stovetop',microwave:'Microwave',oven:'Oven',airfryer:'Air fryer',blender:'Blender',toaster:'Toaster',knife:'Knife & cutting board',slowcooker:'Slow cooker'};
const money=(cents,currency='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency}).format(cents/100);
async function api(path,body,method=body===undefined?'GET':'POST'){const r=await fetch('/api'+path,{method,credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed.');return data;}
function CheckGroup({title,options,values,onChange}){return <fieldset><legend>{title}</legend><div className="checklist">{options.map(o=>{const [value,label]=Array.isArray(o)?o:[o,o];return <label key={value}><input type="checkbox" checked={values.includes(value)} onChange={e=>onChange(e.target.checked?[...values,value]:values.filter(x=>x!==value))}/>{label}</label>})}</div></fieldset>}
function App(){
 const [config,setConfig]=useState(null),[user,setUser]=useState(null),[profile,setProfile]=useState(null),[pantry,setPantry]=useState({}),[tab,setTab]=useState('Preferences'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[login,setLogin]=useState(false),[storeData,setStoreData]=useState(null),[chat,setChat]=useState(''),[proposal,setProposal]=useState(null),[recipe,setRecipe]=useState(null),[recipeStep,setRecipeStep]=useState(0),[wizard,setWizard]=useState(0);const dialog=useRef(null),chatEnd=useRef(null);
 async function refresh(){const u=await api('/me');setUser(u);setProfile(u.profile);setPantry(u.pantry);return u;}
 useEffect(()=>{api('/config').then(setConfig).catch(e=>setError(e.message));api('/me').then(u=>{setUser(u);setProfile(u.profile);setPantry(u.pantry)}).catch(e=>{if(!/sign in|session expired/i.test(e.message))setError(e.message)}).finally(()=>setLoaded(true));},[]);
 useEffect(()=>{if(recipe){setRecipeStep(0);dialog.current?.showModal();}},[recipe]);
 useEffect(()=>chatEnd.current?.scrollIntoView({behavior:'smooth',block:'nearest'}),[user?.chats]);
 async function run(fn){setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 function field(key,value){setProfile(p=>({...p,[key]:value}))}
 async function saveProfile(){await api('/profile',profile,'PUT');await refresh();setNotice('Preferences saved. Existing plans keep their original settings until you generate a new week.');}
 async function generateWeek(){await api('/profile',profile,'PUT');await api('/plans',{});await refresh();setTab('My week');setNotice('Your new week is ready.');}
 async function searchStores(coords){const data=await api('/stores',{country:profile.country,location:profile.location,...coords});setStoreData(data);if(!data.stores.length)setNotice('No stores found within 15 km. Try another city or postal code.');}
 function locate(){setError('');if(!navigator.geolocation){setError('Location is unavailable. Enter a city or postal code instead.');return;}navigator.geolocation.getCurrentPosition(p=>run(()=>searchStores({lat:p.coords.latitude,lon:p.coords.longitude})),()=>setError('Location was not shared. You can enter your city or postal code instead.'),{enableHighAccuracy:false,timeout:12000,maximumAge:60000});}
 async function submitChat(e){e.preventDefault();const message=chat.trim();if(!message)return;await run(async()=>{const result=await api('/chat',{message});setChat('');setProposal(result.actionToken?result:null);await refresh();});}
 const plan=user?.plan,currency=profile?.country==='CA'?'CAD':'USD';
 return <><header><a className="brand" href="/">CC <span>Cheap Chef</span></a><div className="row">{user?<><span className="muted">{user.email}</span><button className="secondary" disabled={busy} onClick={()=>run(async()=>{await api('/logout',{});setUser(null);setProfile(null);setProposal(null);setStoreData(null);})}>Sign out</button></>:<span>Your kitchen, your rules.</span>}</div></header><main>
 {error&&<div role="alert" className="error">{error}</div>}{notice&&<div role="status" className="success">{notice}</div>}
 {!loaded||!config?<section className="panel"><p>Connecting to your kitchen…</p></section>:!user?<><section className="intro"><div><p className="eyebrow">YOUR PERSONAL KITCHEN COMPANION</p><h1>A good week<br/>starts here.</h1><p>Meals that fit your life. A grocery list that respects your budget.</p><button onClick={()=>document.querySelector('#email')?.focus()}>Build my week →</button></div><img src="/assets/meal-prep.png" alt="A spread of prepared meals and fresh ingredients"/></section><section className="panel" style={{maxWidth:560}}><h2>{login?'Welcome back.':'Make yourself at home.'}</h2><p>{login?'Sign in to your kitchen.':'Create an account to save your pantry, preferences and weekly plans.'}</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await api(login?'/login':'/register',{email:f.get('email'),password:f.get('password')});await refresh();})}}><label>Email<input id="email" name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" minLength={12} maxLength={128} autoComplete={login?'current-password':'new-password'} required/></label><p className="muted">Use at least 12 characters. Email verification and password recovery are not available in this beta.</p>{!login&&<label><input type="checkbox" required/>I am 18 or older.</label>}<div className="row"><button disabled={busy}>{busy?'Please wait…':login?'Sign in':'Create account'}</button><button type="button" className="secondary" onClick={()=>setLogin(!login)}>{login?'Create an account':'Already registered?'}</button></div></form></section></>:<>
 <div className="row" style={{justifyContent:'space-between',marginTop:20}}><div><p className="eyebrow">YOUR WEEK, MADE SIMPLER</p><h1 style={{fontSize:'2.5rem'}}>Let’s get cooking{profile.name?`, ${profile.name}`:''}.</h1></div><button disabled={busy} onClick={()=>run(generateWeek)}>Build a new week →</button></div>
 <nav aria-label="Kitchen sections">{['Preferences','Nearby stores','Pantry','My week','Shopping list','AI chef','Account'].map(t=><button key={t} className={tab===t?'active':''} aria-current={tab===t?'page':undefined} onClick={()=>{setTab(t);setNotice('')}}>{t}</button>)}</nav>
 {tab==='Preferences'&&<section className="panel"><div className="row" style={{justifyContent:'space-between'}}><h2>Make it yours.</h2><span className="tag">Step {wizard+1} of 3</span></div><div className="row">{['About you','Your kitchen','Your food'].map((s,i)=><button key={s} className="secondary" onClick={()=>setWizard(i)}>{i+1}. {s}</button>)}</div><form onSubmit={e=>{e.preventDefault();run(saveProfile)}}>
 {wizard===0&&<><div className="grid"><label>First name<input value={profile.name} maxLength={80} onChange={e=>field('name',e.target.value)}/></label><label>Country<select value={profile.country} onChange={e=>{field('country',e.target.value);field('stores',[]);setStoreData(null)}}><option value="US">United States · USD</option><option value="CA">Canada · CAD</option></select></label><label>City, state/province or postal code<input value={profile.location} maxLength={150} onChange={e=>field('location',e.target.value)} placeholder="Columbus, Ohio or 43210"/></label><label>Weight (kg)<input type="number" min={40} max={250} value={profile.weight} onChange={e=>field('weight',+e.target.value)}/></label><label>Height (cm)<input type="number" min={130} max={230} value={profile.height} onChange={e=>field('height',+e.target.value)}/></label><label>Nutrition goal<select value={profile.goal} onChange={e=>field('goal',e.target.value)}><option value="maintain">Maintain weight</option><option value="lose">Lose weight</option><option value="gain">Gain weight</option></select></label></div><p className="muted">Adult planning estimates only. Height and weight alone cannot determine your exact calorie needs. The plan’s calorie and macro values are approximate.</p></>}
 {wizard===1&&<><div className="grid"><label>Weekly grocery budget ({currency})<input type="number" min={1} max={2000} step=".01" value={profile.budget} onChange={e=>field('budget',+e.target.value)}/></label><label>Maximum cooking time (minutes)<input type="number" min={5} max={180} value={profile.minutes} onChange={e=>field('minutes',+e.target.value)}/></label><label>Meals per day<select value={profile.meals} onChange={e=>field('meals',+e.target.value)}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label></div><CheckGroup title="Available kitchen equipment" options={Object.entries(equipment)} values={profile.equipment} onChange={v=>field('equipment',v)}/><p className="muted">The current recipe collection mainly uses a stovetop and cutting board. Restrictive equipment or time choices may not have enough recipes for a full week.</p></>}
 {wizard===2&&<><label>Diet<select value={profile.diet} onChange={e=>field('diet',e.target.value)}>{['none','vegan','vegetarian','halal','kosher'].map(x=><option key={x} value={x}>{x==='none'?'No preference':x[0].toUpperCase()+x.slice(1)}</option>)}</select></label><CheckGroup title="Ingredients to avoid" options={['wheat','soy','milk','eggs','peanuts','tree nuts','fish','shellfish','sesame','mustard','pork']} values={profile.allergens} onChange={v=>field('allergens',v)}/><CheckGroup title="Preferred cuisines (leave empty for all)" options={['American','Italian','Mexican','Middle Eastern','Asian']} values={profile.cuisines} onChange={v=>field('cuisines',v)}/><p className="muted">Halal and kosher settings use plant-based recipes; certification is not verified. Check ingredient certifications, product labels and cross-contact warnings. Recipe variations share some staple ingredients.</p></>}
 <div className="row" style={{marginTop:20}}>{wizard>0&&<button className="secondary" type="button" onClick={()=>setWizard(wizard-1)}>Back</button>}{wizard<2?<button type="button" onClick={()=>setWizard(wizard+1)}>Next →</button>:<button disabled={busy}>Save preferences</button>}</div></form></section>}
 {tab==='Nearby stores'&&<section className="panel"><h2>Your neighborhood, your stores.</h2><p>Search within 15 km of your location. Choose the branches you shop at.</p><div className="grid"><label>Country<select value={profile.country} onChange={e=>{field('country',e.target.value);field('stores',[]);setStoreData(null)}}><option value="US">United States</option><option value="CA">Canada</option></select></label><label>City, ZIP or postal code<input value={profile.location} onChange={e=>field('location',e.target.value)}/></label></div><div className="row"><button disabled={busy} onClick={()=>run(()=>searchStores())}>Find nearby stores</button><button className="secondary" disabled={busy} onClick={locate}>Use my location</button></div><p className="muted">Only shared when you search. Location searches go to OpenStreetMap services. Device location is optional; distances are straight-line, not driving distance.</p><CheckGroup title="Warehouse memberships" options={['Costco',"Sam's Club"]} values={profile.memberships} onChange={v=>field('memberships',v)}/><div className="grid">{(storeData?.stores||profile.stores).map(s=><label className="card" key={s.id}><input type="checkbox" checked={profile.stores.some(x=>x.id===s.id)} onChange={e=>field('stores',e.target.checked?[...profile.stores,s]:profile.stores.filter(x=>x.id!==s.id))}/>{s.name}<p className="muted">{s.address}</p><span className="tag">{(s.distance/1000).toFixed(1)} km away</span>{s.warehouse&&<span className="tag">Membership store</span>}<a className="small" href={`https://www.openstreetmap.org/?mlat=${s.lat}&mlon=${s.lon}#map=17/${s.lat}/${s.lon}`} target="_blank" rel="noreferrer">View location ↗</a></label>)}</div>{!storeData&&!profile.stores.length&&<p className="muted">Search to see available branches. We won’t show generic chains as nearby locations.</p>}<button disabled={busy} onClick={()=>run(saveProfile)} style={{marginTop:20}}>Save selected stores ({profile.stores.length})</button><p className="muted">Map data © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap contributors</a>. Coverage may be incomplete. Store prices and stock are not connected.</p></section>}
 {tab==='Pantry'&&<section className="panel"><h2>Use what you already have.</h2><p>Enter the amount left in grams. Only missing quantities go on your next shopping list.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/pantry',pantry,'PUT');await refresh();setNotice('Pantry saved. It will be used when generating your next plan.');})}}><div className="grid">{Object.entries(config.ingredients).map(([id,x])=><label key={id}>{x.name}<input type="number" min={0} max={100000} step="1" value={pantry[id]||0} onChange={e=>setPantry({...pantry,[id]:+e.target.value})}/><span className="muted">grams · typical pack {x.pack} g</span></label>)}</div><button disabled={busy}>Save pantry</button></form></section>}
 {['My week','Shopping list'].includes(tab)&&(!plan?<section className="panel"><h2>Your first week is waiting.</h2><p>Save your preferences and pantry, then build a week.</p><button disabled={busy} onClick={()=>run(generateWeek)}>Build my week</button></section>:<><section className="panel"><div className="grid"><div><p className="muted">Estimated grocery total</p><p className="stat">{money(plan.totalCents,plan.currency)}</p></div><div><p className="muted">Budget remaining</p><p className="stat">{money(Math.round(plan.settings.budget*100)-plan.totalCents,plan.currency)}</p></div><div><p className="muted">Approximate daily calorie target</p><p className="stat">{plan.targetCalories} kcal</p></div></div><p className="muted">{plan.priceNote}</p><p className="muted">Plan created {new Date(plan.createdAt).toLocaleDateString()}. Based on saved settings at creation.</p></section>
 {tab==='My week'?days.map((day,d)=><section key={day} style={{marginBottom:28}}><h2>{day}</h2><div className="grid">{plan.meals.slice(d*plan.settings.meals,(d+1)*plan.settings.meals).map((m,j)=>{const i=d*plan.settings.meals+j;return <article key={i} className="card meal"><img src={m.image} alt="Illustrative prepared meal spread" loading="lazy"/><p className="small muted">Illustrative photo</p><h3>{m.name}</h3><p><span className="tag">{m.minutes} min</span><span className="tag">{m.nutrition.kcal} kcal</span></p><p className="muted">{m.nutrition.protein} g protein · {m.nutrition.carbs} g carbs · {m.nutrition.fat} g fat</p><div className="row"><button onClick={()=>setRecipe({m,index:i})}>Let’s cook</button><button className="secondary" disabled={busy||plan.purchased||plan.completed.length>0} onClick={()=>run(async()=>{await api('/plans/swap',{index:i});await refresh()})}>Swap</button></div>{plan.completed.includes(i)&&<p className="success">Cooked · pantry updated</p>}</article>})}</div></section>):<section className="panel"><h2>Your shopping list.</h2><p>{plan.stores?.length?'Preferred branches: '+plan.stores.map(s=>s.name).join(', '):'No store selected. Choose branches in Nearby stores for your next plan.'}</p><p className="muted">This list uses the same illustrative prices for all branches. Bulk pack comparisons and live stock checks are not available.</p>{plan.list.filter(x=>x.packages>0).map(x=><label className="card row" style={{justifyContent:'space-between'}} key={x.id}><span><input type="checkbox"/>{x.name}<small style={{display:'block'}}>{x.packages} × {x.packGrams} g pack · need {x.needed} g · pantry covers {x.pantryUsed} g</small></span><strong>{money(x.cents,plan.currency)}</strong></label>)}{plan.list.every(x=>x.packages===0)&&<p>Your pantry covers this entire week.</p>}<details><summary>Ingredients covered by your pantry</summary>{plan.list.filter(x=>!x.packages).map(x=><p key={x.id}>{x.name}: {x.pantryUsed} g</p>)}</details><div className="row" style={{marginTop:20}}><button disabled={busy||plan.purchased} onClick={()=>run(async()=>{await api('/plans/purchased',{});await refresh();setNotice('Purchased quantities added to your pantry. Mark meals cooked to deduct ingredients.');})}>{plan.purchased?'Purchases recorded':'I bought everything — update pantry'}</button><button className="secondary" onClick={()=>window.print()}>Print list</button></div><p className="muted">Record purchases only after you buy them. If amounts differ, edit your pantry manually.</p></section>}</>)}
 {tab==='AI chef'&&<section className="panel"><h2>Meet your kitchen companion.</h2><p>Ask about your meals, request a swap, or talk through a new week.</p><p className={config.ai?'muted':'error'}>{config.ai?'Your messages and meal preferences are sent to the AI provider when you chat. Suggested changes need your confirmation.':'AI is not connected yet. Planning and recipe controls still work; chat will not pretend to be an AI.'}</p><div className="chatlog" aria-live="polite">{user.chats.length?user.chats.map((m,i)=><div className={'bubble '+m.role} key={i}><strong>{m.role==='user'?'You':'Chef'}</strong><p>{m.text}</p></div>):<div className="bubble">Try “Plan my week for $75,” or “How do I cook Monday’s first meal?”</div>}<div ref={chatEnd}/></div>{proposal&&<div className="card"><p>Suggested action: {proposal.action}{proposal.budget!==null?` · budget ${money(proposal.budget*100,currency)}`:''}{proposal.minutes!==null?` · ${proposal.minutes} minutes`:''}{proposal.cuisines?` · ${proposal.cuisines.join(', ')}`:''}{proposal.mealIndex!==null?` · meal ${proposal.mealIndex+1}`:''}</p><div className="row"><button disabled={busy} onClick={()=>run(async()=>{const r=await api('/chat/confirm',{token:proposal.actionToken});setProposal(null);await refresh();setNotice(r.message);})}>Apply suggestion</button><button className="secondary" onClick={()=>setProposal(null)}>Dismiss</button></div></div>}<form onSubmit={submitChat}><label>Your message<textarea maxLength={2000} value={chat} onChange={e=>setChat(e.target.value)} rows={3} placeholder="What would you like to cook?" required/></label><button disabled={busy||!chat.trim()}>{busy?'Working…':'Send to chef →'}</button></form></section>}
 {tab==='Account'&&<section className="panel"><h2>Your account</h2><p>{user.email}</p><p>Preferences, pantry quantities, plans and chat messages are saved to your account. Email verification and password recovery are not yet available.</p><details><summary className="danger">Delete account and saved data</summary><p>This permanently deletes your account, pantry, plans and chat history.</p><form onSubmit={e=>{e.preventDefault();const password=new FormData(e.currentTarget).get('password');run(async()=>{await api('/account',{password},'DELETE');setUser(null);setProfile(null);})}}><label>Confirm your password<input name="password" type="password" required/></label><label><input type="checkbox" required/>Delete my account and all saved data permanently.</label><button disabled={busy}>Delete my account</button></form></details></section>}
 </>}
 <footer>Cheap Chef beta · Planning estimates, not live store quotes. Check food labels for allergens. <a href="https://github.com/anasajhani/cheap-chef" target="_blank" rel="noreferrer">Project on GitHub ↗</a></footer>
 <dialog ref={dialog} onClose={()=>setRecipe(null)}>{recipe&&<><div className="row" style={{justifyContent:'space-between'}}><h2>{recipe.m.name}</h2><button className="secondary" onClick={()=>dialog.current.close()}>Close</button></div><p>{recipe.m.minutes} minutes · {recipe.m.nutrition.kcal} kcal · equipment: {recipe.m.equipment.map(x=>equipment[x]).join(', ')}</p><img src={recipe.m.image} alt="Illustrative prepared meals" style={{width:'100%',height:160,objectFit:'cover',borderRadius:12}}/><p className="muted">{recipe.m.imageNote}</p><h3>Ingredients for your portion</h3><ul>{Object.entries(recipe.m.items).map(([id,g])=><li key={id}>{g} g {config.ingredients[id].name.toLowerCase()}</li>)}</ul><h3>Step {recipeStep+1} of {recipe.m.steps.length}</h3><p className="card">{recipe.m.steps[recipeStep]}</p><div className="row"><button className="secondary" disabled={recipeStep===0} onClick={()=>setRecipeStep(recipeStep-1)}>Previous</button>{recipeStep<recipe.m.steps.length-1?<button onClick={()=>setRecipeStep(recipeStep+1)}>Next step →</button>:<button disabled={busy||plan?.completed.includes(recipe.index)} onClick={()=>run(async()=>{await api('/plans/cooked',{index:recipe.index});await refresh();dialog.current.close();setNotice('Meal marked cooked. Pantry quantities updated.');})}>I cooked this — update pantry</button>}</div></>}</dialog>
 </main></>;
}
createRoot(document.getElementById('root')).render(<App/>);
