import {z} from 'zod';
import {ingredients,recipes,nutrients} from './catalog.js';
export const profileSchema=z.object({name:z.string().trim().max(80).default(''),country:z.enum(['US','CA']).default('US'),location:z.string().max(150).default(''),weight:z.number().min(40).max(250).default(70),height:z.number().min(130).max(230).default(170),goal:z.enum(['lose','maintain','gain']).default('maintain'),budget:z.number().min(1).max(2000).default(75),minutes:z.number().int().min(5).max(180).default(45),meals:z.number().int().min(1).max(4).default(3),equipment:z.array(z.enum(['stovetop','microwave','oven','airfryer','blender','toaster','knife','slowcooker'])).max(8).default(['stovetop','knife']),diet:z.enum(['none','vegan','vegetarian','halal','kosher']).default('none'),allergens:z.array(z.enum(['wheat','soy','milk','eggs','peanuts','tree nuts','fish','shellfish','sesame','mustard','pork'])).max(11).default([]),cuisines:z.array(z.enum(['American','Italian','Mexican','Middle Eastern','Asian'])).max(5).default([]),memberships:z.array(z.enum(['Costco',"Sam's Club"])).max(2).default([]),stores:z.array(z.object({id:z.string().max(100),name:z.string().max(200),address:z.string().max(400),distance:z.number().min(0).nullable(),lat:z.number().min(-90).max(90),lon:z.number().min(-180).max(180),warehouse:z.boolean()})).max(10).default([]),adult:z.literal(true).default(true)});
export const defaults=profileSchema.parse({});
export const pantrySchema=z.partialRecord(z.enum(Object.keys(ingredients)),z.number().min(0).max(100000));
export function target(p){return Math.round(Math.min(3600,Math.max(1600,(10*p.weight+6.25*p.height-150)*1.4+(p.goal==='lose'?-250:p.goal==='gain'?250:0)))/50)*50;}
export function eligible(p){return recipes.filter(r=>r.minutes<=p.minutes&&r.equipment.every(e=>p.equipment.includes(e))&&(p.diet==='none'||r.vegan)&&!Object.keys(r.items).some(k=>ingredients[k].allergens.some(a=>p.allergens.includes(a)))&&(!p.cuisines.length||p.cuisines.includes(r.cuisine)));}
export function portion(r,p){const scale=target(p)/p.meals/r.nutrition.kcal;if(scale<.4||scale>3.5)return null;const items=Object.fromEntries(Object.entries(r.items).map(([k,v])=>[k,Math.round(v*scale)]));return {...r,items,nutrition:nutrients(items),portionScale:Math.round(scale*100)/100};}
export function shopping(meals,p,pantry={}){const need={};for(const m of meals)for(const [id,g] of Object.entries(m.items))need[id]=(need[id]||0)+g;const list=Object.entries(need).map(([id,g])=>{const item=ingredients[id],stock=pantry[id]||0,missing=Math.max(0,g-stock),packages=Math.ceil(missing/item.pack),unitPrice=Math.round(item[p.country==='CA'?'cad':'usd']*100);return {id,name:item.name,needed:g,pantryUsed:Math.min(g,stock),packages,packGrams:item.pack,buyGrams:packages*item.pack,leftover:Math.max(0,stock-g)+packages*item.pack-missing,cents:packages*unitPrice};});return {list,totalCents:list.reduce((n,x)=>n+x.cents,0),currency:p.country==='CA'?'CAD':'USD',priceNote:'Illustrative package prices, not store quotes. Taxes, deposits, membership fees and local price changes are not included.',stores:p.stores};}
export function validatePlan(meals,p,pantry){const allowed=new Set(eligible(p).map(r=>r.id));if(meals.length!==7*p.meals||meals.some(m=>!allowed.has(m.id)))throw new Error('The requested plan does not meet your meal, diet, time or equipment settings.');const bill=shopping(meals,p,pantry);if(bill.totalCents>Math.floor(p.budget*100))throw new Error('No plan found within your budget and current preferences. Try a larger budget or different cuisines/equipment. Your existing plan has not changed.');return bill;}
export function generate(p,pantry={},previous=[]){const old=new Set(previous.map(m=>m.id));const pool=eligible(p).filter(r=>!old.has(r.id)).map(r=>portion(r,p)).filter(Boolean);if(pool.length<7*p.meals)throw new Error('There are not enough different recipes for a full week without repeating the previous plan. Broaden your cuisines or equipment, or reduce the meals per day.');let best;for(let attempt=0;attempt<80;attempt++){const ranked=pool.map(r=>({r,score:shopping([r],p,pantry).totalCents*(.6+Math.random()*.8)})).sort((a,b)=>a.score-b.score);const chosen=ranked.slice(0,7*p.meals).map(x=>x.r);const bill=shopping(chosen,p,pantry);if(!best||bill.totalCents<best.totalCents)best={meals:chosen,...bill};if(bill.totalCents<=p.budget*100)break;}validatePlan(best.meals,p,pantry);return {...best,targetCalories:target(p),settings:p,completed:[],createdAt:new Date().toISOString()};}
export function swap(plan,index,p,pantry,previous=[]){if(!Number.isInteger(index)||index<0||index>=plan.meals.length)throw new Error('Choose a valid meal to replace.');const excluded=new Set([...plan.meals,...previous].map(m=>m.id));for(const r of eligible(p).filter(r=>!excluded.has(r.id))){const m=portion(r,p);if(!m)continue;const meals=plan.meals.map((x,i)=>i===index?m:x);try{const bill=validatePlan(meals,p,pantry);return {...plan,...bill,meals};}catch{}}throw new Error('No replacement fits all your current constraints and budget.');}
