import express from 'express';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import {rateLimit} from 'express-rate-limit';
import {randomUUID,randomBytes,scrypt as scryptCb,timingSafeEqual,createHash} from 'node:crypto';
import {promisify} from 'node:util';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {z} from 'zod';
import {database} from './db.js';
import {ingredients} from './catalog.js';
import {defaults,profileSchema,pantrySchema,generate,swap,shopping} from './planner.js';
import {findStores} from './stores.js';
import {askChef,actionSchema} from './chef.js';
const scrypt=promisify(scryptCb),hash=x=>createHash('sha256').update(x).digest('hex');
export async function createApp(db,{testing=false}={}){
 const app=express(),locks=new Map(),pending=new Map(),searchResults=new Map();
 app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:{directives:{'img-src':["'self'",'data:'],'script-src':["'self'"],'upgrade-insecure-requests':process.env.NODE_ENV==='production'?[]:null}}}));app.use(express.json({limit:'48kb'}));app.use(cookieParser());
 app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(!['GET','HEAD','OPTIONS'].includes(req.method)){const allowed=[process.env.WEB_ORIGIN||'http://localhost:5173',`http://localhost:${process.env.PORT||4000}`,'http://127.0.0.1:5173'];if(!testing&&!allowed.includes(req.get('origin')))return res.status(403).json({error:'Please use the app from its configured address.'});}next();});
 const authLimit=rateLimit({windowMs:15*60000,limit:20,skip:()=>testing,standardHeaders:true,legacyHeaders:false,message:{error:'Too many sign-in attempts. Try again in 15 minutes.'}});
 app.get('/api/health',async(req,res)=>{await db.query('SELECT 1');res.json({ok:true});});
 app.get('/api/config',(req,res)=>res.json({ai:!!(process.env.OPENAI_API_KEY&&process.env.OPENAI_MODEL),ingredients,defaults}));
 async function session(res,id){const token=randomBytes(32).toString('hex');await db.query('INSERT INTO sessions(token,user_id,expires_at) VALUES($1,$2,$3)',[hash(token),id,new Date(Date.now()+7*86400000)]);res.cookie('cc_session',token,{httpOnly:true,secure:process.env.COOKIE_SECURE==='true',sameSite:'lax',maxAge:7*86400000,path:'/'});}
 const credentials=z.object({email:z.email().max(254).transform(x=>x.toLowerCase()),password:z.string().min(12).max(128)});
 app.post('/api/register',authLimit,async(req,res)=>{const {email,password}=credentials.parse(req.body),salt=randomBytes(16).toString('hex'),derived=await scrypt(password,salt,64),id=randomUUID();try{await db.query('INSERT INTO users(id,email,password,profile) VALUES($1,$2,$3,$4)',[id,email,`${salt}:${derived.toString('hex')}`,JSON.stringify(defaults)]);}catch(e){if(e.code==='23505')return res.status(409).json({error:'Unable to create that account. Try signing in instead.'});throw e;}await session(res,id);res.status(201).json({ok:true});});
 app.post('/api/login',authLimit,async(req,res)=>{const {email,password}=credentials.parse(req.body);const user=(await db.query('SELECT * FROM users WHERE email=$1',[email])).rows[0];const [salt,key]=(user?.password||`${'0'.repeat(32)}:${'0'.repeat(128)}`).split(':');const derived=await scrypt(password,salt,64);if(!user||!timingSafeEqual(derived,Buffer.from(key,'hex')))return res.status(401).json({error:'Email or password is incorrect.'});await session(res,user.id);res.json({ok:true});});
 app.use('/api',async(req,res,next)=>{const token=req.cookies.cc_session;if(!token)return res.status(401).json({error:'Please sign in.'});const row=(await db.query('SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token=$1 AND s.expires_at>NOW()',[hash(token)])).rows[0];if(!row)return res.status(401).json({error:'Your session expired. Please sign in again.'});req.user=row;next();});
 // Serialize mutations per account so pantry deductions and plan writes do not race in this process.
 app.use('/api',async(req,res,next)=>{if(req.method==='GET')return next();const id=req.user.id,previous=locks.get(id)||Promise.resolve();let release;const current=new Promise(r=>release=r);locks.set(id,current);await previous;const done=()=>{release();if(locks.get(id)===current)locks.delete(id);};res.once('finish',done);res.once('close',done);req.user=(await db.query('SELECT * FROM users WHERE id=$1',[id])).rows[0];if(!req.user)return res.status(401).json({error:'Account no longer exists.'});next();});
 async function plans(id){return(await db.query('SELECT id,data FROM plans WHERE user_id=$1 ORDER BY created_at DESC,id DESC LIMIT 2',[id])).rows;}
 async function save(id,data,planId,connection=db){if(planId)await connection.query('UPDATE plans SET data=$1 WHERE id=$2 AND user_id=$3',[JSON.stringify(data),planId,id]);else{planId=randomUUID();await connection.query('INSERT INTO plans(id,user_id,data) VALUES($1,$2,$3)',[planId,id,JSON.stringify(data)]);}return {id:planId,...data};}
 app.get('/api/me',async(req,res)=>{const ps=await plans(req.user.id);res.json({email:req.user.email,profile:req.user.profile,pantry:req.user.pantry,plan:ps[0]?{id:ps[0].id,...ps[0].data}:null,chats:(await db.query('SELECT role,text FROM chats WHERE user_id=$1 ORDER BY created_at DESC,id DESC LIMIT 24',[req.user.id])).rows.reverse()});});
 app.post('/api/logout',async(req,res)=>{await db.query('DELETE FROM sessions WHERE token=$1',[hash(req.cookies.cc_session)]);res.clearCookie('cc_session',{path:'/'});res.json({ok:true});});
 app.delete('/api/account',async(req,res)=>{const {password}=z.object({password:z.string().max(128)}).parse(req.body);const [salt,key]=req.user.password.split(':');if(!timingSafeEqual(await scrypt(password,salt,64),Buffer.from(key,'hex')))return res.status(401).json({error:'Password is incorrect.'});await db.query('DELETE FROM users WHERE id=$1',[req.user.id]);pending.delete(req.user.id);searchResults.delete(req.user.id);res.clearCookie('cc_session',{path:'/'});res.json({ok:true});});
 app.put('/api/profile',async(req,res)=>{const p=profileSchema.parse(req.body);const trusted=[...req.user.profile.stores||[],...searchResults.get(req.user.id)?.stores||[]];p.stores=p.stores.map(s=>{const verified=trusted.find(x=>x.id===s.id);if(!verified)throw new Error('Search for nearby stores before selecting them.');return verified;});await db.query('UPDATE users SET profile=$1 WHERE id=$2',[JSON.stringify(p),req.user.id]);res.json(p);});
 app.put('/api/pantry',async(req,res)=>{const pantry=pantrySchema.parse(req.body);await db.query('UPDATE users SET pantry=$1 WHERE id=$2',[JSON.stringify(pantry),req.user.id]);res.json(pantry);});
 app.post('/api/plans',async(req,res)=>{const ps=await plans(req.user.id);res.json(await save(req.user.id,generate(profileSchema.parse(req.user.profile),req.user.pantry,ps[0]?.data.meals||[])));});
 app.post('/api/plans/swap',async(req,res)=>{const {index}=z.object({index:z.number().int().min(0).max(27)}).parse(req.body),ps=await plans(req.user.id);if(!ps[0])throw new Error('Generate a plan first.');if(ps[0].data.purchased||ps[0].data.completed?.length)throw new Error('Start a new plan to make changes after shopping or cooking.');res.json(await save(req.user.id,swap(ps[0].data,index,profileSchema.parse(req.user.profile),req.user.pantry,ps[1]?.data.meals||[]),ps[0].id));});
 app.post('/api/plans/purchased',async(req,res)=>{const ps=await plans(req.user.id);if(!ps[0])throw new Error('Generate a plan first.');const plan=ps[0].data;if(plan.purchased)throw new Error('These purchases have already been added.');const pantry={...req.user.pantry};for(const x of plan.list)pantry[x.id]=(pantry[x.id]||0)+x.buyGrams;plan.purchased=true;await db.transaction(async tx=>{await tx.query('UPDATE users SET pantry=$1 WHERE id=$2',[JSON.stringify(pantry),req.user.id]);await save(req.user.id,plan,ps[0].id,tx);});res.json({ok:true});});
 app.post('/api/plans/cooked',async(req,res)=>{const {index}=z.object({index:z.number().int().min(0).max(27)}).parse(req.body),ps=await plans(req.user.id);if(!ps[0]||!ps[0].data.meals[index])throw new Error('Choose a valid meal.');const plan=ps[0].data;if(plan.completed.includes(index))throw new Error('This meal is already marked cooked.');const pantry={...req.user.pantry};for(const [id,g] of Object.entries(plan.meals[index].items)){if((pantry[id]||0)<g)throw new Error('Pantry stock is too low. Record your purchases or update your pantry first.');pantry[id]-=g;}plan.completed.push(index);await db.transaction(async tx=>{await tx.query('UPDATE users SET pantry=$1 WHERE id=$2',[JSON.stringify(pantry),req.user.id]);await save(req.user.id,plan,ps[0].id,tx);});res.json({ok:true});});
 app.post('/api/stores',rateLimit({windowMs:60000,limit:5,skip:()=>testing,message:{error:'Please wait a minute before searching again.'}}),async(req,res)=>{const data=z.object({country:z.enum(['US','CA']),location:z.string().max(150).optional(),lat:z.number().min(-90).max(90).optional(),lon:z.number().min(-180).max(180).optional()}).refine(x=>(x.lat===undefined)===(x.lon===undefined)).parse(req.body);const result=await findStores(data);if(searchResults.size>1000)searchResults.delete(searchResults.keys().next().value);searchResults.set(req.user.id,result);res.json(result);});
 app.post('/api/chat',rateLimit({windowMs:60000,limit:8,skip:()=>testing,message:{error:'Please wait a minute before asking again.'}}),async(req,res)=>{const {message}=z.object({message:z.string().trim().min(1).max(2000)}).parse(req.body);if(process.env.OPENAI_API_KEY&&process.env.OPENAI_MODEL){const day=new Date().toISOString().slice(0,10);const usage=await db.query('INSERT INTO usage(user_id,day,calls) VALUES($1,$2,1) ON CONFLICT(user_id,day) DO UPDATE SET calls=usage.calls+1 RETURNING calls',[req.user.id,day]);if(usage.rows[0].calls>Number(process.env.AI_DAILY_LIMIT||20))return res.status(429).json({error:'You have reached today’s AI message allowance. Meal-planning controls are still available.'});}const ps=await plans(req.user.id),history=(await db.query('SELECT role,text FROM chats WHERE user_id=$1 ORDER BY created_at DESC,id DESC LIMIT 12',[req.user.id])).rows.reverse();const answer=await askChef({message,history,profile:req.user.profile,pantry:req.user.pantry,plan:ps[0]?.data});await db.query('INSERT INTO chats(id,user_id,role,text) VALUES($1,$2,$3,$4)',[randomUUID(),req.user.id,'user',message]);await db.query('INSERT INTO chats(id,user_id,role,text) VALUES($1,$2,$3,$4)',[randomUUID(),req.user.id,'assistant',answer.reply]);let actionToken=null;if(answer.action!=='none'){actionToken=randomUUID();pending.set(req.user.id,{answer,token:actionToken,expires:Date.now()+10*60000,planId:ps[0]?.id,planHash:hash(JSON.stringify(ps[0]?.data||null)),profile:JSON.stringify(req.user.profile)});}res.json({...answer,actionToken});});
 app.post('/api/chat/confirm',async(req,res)=>{const {token}=z.object({token:z.string().uuid()}).parse(req.body),proposal=pending.get(req.user.id);if(!proposal||proposal.token!==token||proposal.expires<Date.now())throw new Error('That suggestion expired. Ask the chef again.');const a=actionSchema.parse(proposal.answer),ps=await plans(req.user.id);if(proposal.planId!==ps[0]?.id||proposal.planHash!==hash(JSON.stringify(ps[0]?.data||null))||proposal.profile!==JSON.stringify(req.user.profile))throw new Error('Your settings or plan changed. Ask the chef for a new suggestion.');pending.delete(req.user.id);let p=profileSchema.parse(req.user.profile);if(a.action==='preferences'){p=profileSchema.parse({...p,...(a.budget!==null?{budget:a.budget}:{}),...(a.minutes!==null?{minutes:a.minutes}:{}),...(a.cuisines!==null?{cuisines:a.cuisines}:{})});await db.query('UPDATE users SET profile=$1 WHERE id=$2',[JSON.stringify(p),req.user.id]);res.json({message:'Preferences saved. Generate a new week to apply them.'});}else if(a.action==='generate'){await save(req.user.id,generate(p,req.user.pantry,ps[0]?.data.meals||[]));res.json({message:'Your new meal plan and shopping list are ready.'});}else if(a.action==='swap'){if(!ps[0]||ps[0].data.purchased||ps[0].data.completed?.length)throw new Error('Generate a new plan before making this change.');await save(req.user.id,swap(ps[0].data,a.mealIndex,p,req.user.pantry,ps[1]?.data.meals||[]),ps[0].id);res.json({message:'Meal replaced and shopping list updated.'});}else res.json({message:'No change requested.'});});
 app.use('/api',(req,res)=>res.status(404).json({error:'Not found.'}));
 const web=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../web/build');app.use(express.static(web));app.get('/',(req,res)=>res.sendFile(path.join(web,'index.html')));
 app.use((err,req,res,next)=>{if(res.headersSent)return next(err);if(err instanceof z.ZodError)return res.status(400).json({error:err.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; ')});const expected=/^(No |There |The |Choose |Generate |Start |These |This |Pantry |Search |Enter |Location |Invalid |Your |That |Account)/.test(err.message);if(!expected)console.error(err.code||err.name);res.status(expected?422:500).json({error:expected?err.message:'Something went wrong. Please try again.'});});return app;
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const db=await database();const app=await createApp(db);const server=app.listen(Number(process.env.PORT||4000),process.env.HOST||'127.0.0.1',()=>console.log(`Cheap Chef API ready: http://127.0.0.1:${process.env.PORT||4000}`));process.once('SIGTERM',()=>server.close(async()=>{await db.close();process.exit(0);}));}
