const cache=new Map();let queue=Promise.resolve(),lastGeo=0;
function remember(key,value){if(cache.size>500)cache.delete(cache.keys().next().value);cache.set(key,{value,expires:Date.now()+86400000});return value;}
function cached(key){const x=cache.get(key);return x?.expires>Date.now()?x.value:null;}
async function json(url,options={}){const response=await fetch(url,{...options,headers:{'User-Agent':process.env.MAP_USER_AGENT||'CheapChef/1.0 (https://github.com/anasajhani/cheap-chef)',...options.headers},signal:AbortSignal.timeout(25000)});if(!response.ok)throw new Error('The map service is temporarily unavailable. Please try again later.');return response.json();}
export function distance(a,b,c,d){const rad=Math.PI/180;const h=Math.sin((c-a)*rad/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin((d-b)*rad/2)**2;return Math.round(6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h))));}
export async function findStores({country,location,lat,lon}){
 const key=JSON.stringify({country,location,lat,lon});const hit=cached(key);if(hit)return hit;
 if(lat===undefined){if(!location?.trim())throw new Error('Enter a city, ZIP or postal code, or use your location.');const run=async()=>{await new Promise(r=>setTimeout(r,Math.max(0,1100-(Date.now()-lastGeo))));lastGeo=Date.now();return json(`${process.env.NOMINATIM_URL||'https://nominatim.openstreetmap.org'}/search?`+new URLSearchParams({q:location,countrycodes:country.toLowerCase(),format:'jsonv2',limit:'1'}));};const results=await(queue=queue.catch(()=>{}).then(run));if(!results.length)throw new Error('Location not found. Try your city and state/province.');lat=Number(results[0].lat);lon=Number(results[0].lon);}
 if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat < -90||lat >90||lon < -180||lon >180)throw new Error('Invalid location coordinates.');
 const query=`[out:json][timeout:20];(nwr["shop"~"^(supermarket|grocery|wholesale)$"](around:15000,${lat},${lon});nwr["brand"~"Walmart|Target|Kroger|Costco|Sam's Club|ALDI",i]["shop"~"^(supermarket|grocery|wholesale|department_store|general)$"](around:15000,${lat},${lon}););out center tags;`;
 const data=await json(process.env.OVERPASS_URL||'https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({data:query})});
 const stores=(data.elements||[]).map(e=>{const t=e.tags||{},y=e.lat??e.center?.lat,x=e.lon??e.center?.lon;return {id:`osm:${e.type}:${e.id}`,name:t.name||t.brand||'Grocery store',address:[t['addr:housenumber'],t['addr:street'],t['addr:city'],t['addr:state'],t['addr:postcode']].filter(Boolean).join(' ')||'Address not listed in OpenStreetMap',distance:distance(lat,lon,y,x),lat:y,lon:x,warehouse:/costco|sam.s club/i.test(t.name||t.brand||'')};}).filter(s=>Number.isFinite(s.lat)&&Number.isFinite(s.lon)).sort((a,b)=>a.distance-b.distance).filter((s,i,a)=>!a.slice(0,i).some(p=>p.name.toLowerCase()===s.name.toLowerCase()&&distance(p.lat,p.lon,s.lat,s.lon)<100)).slice(0,60);
 return remember(key,{stores,source:'OpenStreetMap contributors',attribution:'https://www.openstreetmap.org/copyright',note:'Within 15 km of the searched location; distances are straight-line. Map coverage can be incomplete. No live prices or inventory.'});
}
